eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:8100/eureka/,http://admin:123@server2:8000/eureka/
server:
  port: 9004
spring:
#服务链路追踪
  zipkin:
    base-url: http://localhost:9031
    
#服务熔断开启
feign:
  hystrix:
    enabled: true
    
