server:
  port: 9100
spring:
  application:
    name: hystrix-dashboard-turbine
turbine:
  appConfig: spring-cloud-consumer1,spring-cloud-consumer2
#  aggregator:
#    clusterConfig: default
  clusterNameExpression: new String("default")
 
eureka: 
  client:
    registerWithEureka: true #注册本工程为服务
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:123@server1:8100/eureka/,http://admin:123@server2:8000/eureka/